version: "3"

services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - EXPORTER_ENDPOINT=http://jaeger:4318
  jaeger:
    image: "jaegertracing/all-in-one:1.53"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true